"""Build a per-environment copy of the browser extension.

The extension is dependency-free plain JS; "building" means copying
apps/browser-extension into a dist directory and regenerating config.js with
the target API base. Load the dist directory as an unpacked extension, or zip
it for store upload.

Usage:
    python scripts/build_extension.py --api-base https://api.example.com \
        [--skip-hosts host1,host2] [--out dist/browser-extension]

skip-hosts defaults to the API host plus the local dev surfaces, so a hosted
build still works against a local dashboard.
"""
from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path
from urllib.parse import urlsplit

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = REPO_ROOT / "apps" / "browser-extension"

CONFIG_TEMPLATE = """\
// WatchIt extension configuration — generated by scripts/build_extension.py.
const WATCHIT_CONFIG = {{
  // Base URL of the WatchIt event API.
  apiBase: {api_base},
  // Hosts (host:port) the extension must never monitor or block — WatchIt's own
  // surfaces (API + guardian dashboard).
  skipHosts: {skip_hosts},
}};
"""

DEFAULT_LOCAL_HOSTS = [
    "127.0.0.1:4849", "localhost:4849",
    "127.0.0.1:4848", "localhost:4848",
]


def build(api_base: str, skip_hosts: list[str] | None, out: Path) -> Path:
    api_base = api_base.rstrip("/")
    if not api_base.startswith(("http://", "https://")):
        raise SystemExit(f"--api-base must be an http(s) URL, got: {api_base}")
    if skip_hosts is None:
        api_host = urlsplit(api_base).netloc
        skip_hosts = list(dict.fromkeys([api_host, *DEFAULT_LOCAL_HOSTS]))
    if out.exists():
        shutil.rmtree(out)
    shutil.copytree(SOURCE_DIR, out)
    (out / "config.js").write_text(
        CONFIG_TEMPLATE.format(
            api_base=json.dumps(api_base),
            skip_hosts=json.dumps(skip_hosts),
        ),
        encoding="utf-8",
    )
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--api-base", required=True, help="API base URL, e.g. https://api.example.com")
    parser.add_argument("--skip-hosts", help="Comma-separated host:port list to never monitor")
    parser.add_argument("--out", default=str(REPO_ROOT / "dist" / "browser-extension"))
    args = parser.parse_args()
    skip_hosts = [h.strip() for h in args.skip_hosts.split(",") if h.strip()] if args.skip_hosts else None
    out = build(args.api_base, skip_hosts, Path(args.out))
    print(f"extension built: {out}")


if __name__ == "__main__":
    main()
